import { chromium } from '../../../libraries/metal-assault/lab/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
const destination = new URL('../../../output/rio-amazonas-escola-qa/', import.meta.url);
await mkdir(destination, { recursive: true });
const served = JSON.parse(await readFile(new URL('../../../output/serve/prototypes__rio-amazonas.json', import.meta.url), 'utf8'));
const base = process.argv[2] || served.url;
const browser = await chromium.launch({ channel: 'chrome', headless: process.env.QA_HEADED !== '1', args: ['--use-angle=metal', '--ignore-gpu-blocklist'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage(); const errors = []; const cases = []; const assets = new Set(); const proof = [];
page.on('pageerror', e => errors.push(e.message));
page.on('response', r => { if (r.url().startsWith(base)) assets.add(r.url()); if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
const check = async (name, action) => { await action(); cases.push({ name, passed: true }); console.log(`OK ${name}`); };
const shot = name => page.screenshot({ path: fileURLToPath(new URL(`${name}.png`, destination)), fullPage: true });
const observe = () => page.evaluate(() => window.__AMAZONAS__.observe());
const mission = () => page.locator('#mission-open').click();
async function preset(name) { await mission(); await page.getByRole('button', { name, exact: true }).click(); await page.waitForTimeout(500); }
async function record() { await mission(); await page.locator('#record-observation').click(); await page.locator('#mission-close').click(); }
let report;
try {
  await check('endereço principal apresenta Geografia Rabisco antes da cena', async () => { const r = await page.goto(base, { waitUntil: 'networkidle' }); assert.equal(r.status(), 200); assert.equal(await page.title(), 'Geografia Rabisco — Amazonas'); assert.equal(await page.locator('canvas').count(), 0); assert.ok(await page.locator('.brand img').evaluate(e => e.complete && e.naturalWidth === 768)); assert.equal(await page.locator('.header-lab').getAttribute('href'), '/laboratorio.html'); assert.equal(await page.locator('link[rel=canonical]').getAttribute('href'), 'https://geografia.rabisco.net/'); assert.equal(await page.locator('.hero .primary').getAttribute('href'), '/laboratorio.html?atividade=margens'); assert.equal(await page.locator('h1').evaluate(e => getComputedStyle(e).fontFamily.split(',')[0]), 'Caveat'); assert.equal(await page.evaluate(() => Boolean(window.dataLayer)), false); });
  await check('compartilhamento possui imagem local com dimensões declaradas', async () => { const src = await page.locator('meta[property="og:image"]').getAttribute('content'); assert.equal(src, 'https://geografia.rabisco.net/marca/og-geografia.jpg'); const dimensions = await page.evaluate(path => new Promise((resolve, reject) => { const img = new Image(); img.onload = () => resolve([img.naturalWidth, img.naturalHeight]); img.onerror = reject; img.src = path; }), '/marca/og-geografia.jpg'); assert.deepEqual(dimensions, [1200, 630]); });
  const response = await page.goto(new URL('escola.html', base).href, { waitUntil: 'networkidle' });
  await check('caderno escolar servido e materiais oficiais renderizados', async () => { assert.equal(response.status(), 200); assert.equal(await page.title(), 'Geografia Rabisco — Amazonas'); assert.ok(await page.locator('.hero img').evaluate(e => e.complete && e.naturalWidth > 1000)); assert.ok(await page.locator('#official-map').evaluate(e => e.complete && e.naturalWidth === 3000)); await shot('caderno-desktop'); });
  await check('leitura distingue mapa, bacia e modelo', async () => { assert.match(await page.locator('#estudar').textContent(), /não a bacia internacional inteira/); assert.match(await page.locator('.model-limit').textContent(), /não representam anos/); assert.match(await page.locator('.model-limit').textContent(), /não é o mapa oficial/); });
  await check('mapa amplia e rola por teclado', async () => { await page.locator('#map-zoom').focus(); await page.keyboard.press('End'); assert.equal(await page.locator('#map-zoom').inputValue(), '3'); assert.ok(await page.locator('.map-window').evaluate(e => e.scrollWidth > e.clientWidth * 2)); await page.locator('.map-window').focus(); await page.keyboard.press('ArrowRight'); await page.waitForTimeout(180); assert.ok(await page.locator('.map-window').evaluate(e => e.scrollLeft > 0)); });
  await check('leituras complementares abrem', async () => { await page.getByText('Da chuva ao rio: o ciclo da água', { exact: true }).click(); assert.equal(await page.locator('#estudar details').first().evaluate(e => e.open), true); });
  await page.locator('.school-tabs a[href="#atividades"]').click();
  await check('atividades acessíveis e sem coleta de identidade', async () => { assert.equal(await page.locator('#atividades').isVisible(), true); assert.equal(await page.locator('#estudar').isVisible(), false); assert.equal(await page.locator('input[type=email],input[type=text],textarea').count(), 0); assert.equal(await page.locator('#quiz fieldset').count(), 5); });
  await check('resposta incorreta orienta e permite tentar novamente', async () => { await page.locator('[name="question-0"][value="1"]').check(); assert.match(await page.locator('#quiz fieldset').first().textContent(), /Retome o conceito/); await page.locator('[name="question-0"][value="0"]').check(); assert.equal(await page.locator('.feedback').first().getAttribute('data-correct'), 'true'); });
  await check('questões operam por teclado com feedback anunciado', async () => { await page.locator('[name="question-0"][value="0"]').focus(); await page.keyboard.press('ArrowRight'); assert.equal(await page.locator('.feedback').first().getAttribute('data-correct'), 'false'); await page.keyboard.press('ArrowLeft'); assert.equal(await page.locator('.feedback').first().getAttribute('data-correct'), 'true'); assert.equal(await page.locator('.feedback').first().getAttribute('role'), 'status'); });
  await check('cinco questões respondidas com explicação', async () => { for (const [i, value] of [0, 1, 2, 2, 0].entries()) await page.locator(`[name="question-${i}"][value="${value}"]`).check(); assert.match(await page.locator('#quiz-status').textContent(), /5 de 5 perguntas respondidas · 5 respostas corretas agora/); assert.equal(await page.locator('.feedback:visible').count(), 5); await shot('atividades-respondidas'); });
  await page.locator('#atividades a[href="/laboratorio.html?atividade=margens"]').click(); await page.waitForFunction(() => window.__AMAZONAS__?.ready);
  await check('investigação das margens inicia pausada', async () => { assert.equal((await observe()).playing, false); assert.equal((await observe()).year, 0); assert.equal(await page.locator('#mission-open').isVisible(), true); });
  await preset('Etapa 0'); await record();
  await preset('Etapa 240');
  await check('comparação das margens mantém as variáveis', async () => { const s = await observe(); assert.equal(s.year, 240); assert.equal(s.flow, 55); assert.equal(s.sediment, 60); assert.equal(s.season, 'normal'); assert.equal(s.playing, false); assert.equal(s.view, 'map'); await page.waitForTimeout(2300); await shot('margens-etapa-240'); });
  await record(); await page.locator('.education-tools a').click(); await page.locator('.school-tabs a[href="#atividades"]').click();
  await check('registros retornam ao caderno e entradas nulas são descartadas', async () => { assert.equal(await page.locator('#records tbody tr').count(), 2); assert.match(await page.locator('#records').textContent(), /240/); await page.evaluate(() => { const key = 'atlas-amazonas-records'; const records = JSON.parse(sessionStorage.getItem(key)); records.push(null, { activity: 'margens' }); sessionStorage.setItem(key, JSON.stringify(records)); }); await page.reload(); assert.equal(await page.locator('#records tbody tr').count(), 2); assert.match(await page.locator('#records').textContent(), /240/); });
  await page.locator('a[href="/laboratorio.html?atividade=cheias"]').click(); await page.waitForFunction(() => window.__AMAZONAS__?.ready);
  await preset('Comparar vazante'); const dry = await observe(); await record(); await preset('Comparar cheia'); const flood = await observe();
  await check('comparação de cheia e vazante controla etapa e corrente', async () => { assert.equal(dry.year, flood.year); assert.equal(dry.flow, flood.flow); assert.equal(dry.sediment, flood.sediment); assert.ok(flood.flooded > dry.flooded); assert.equal(flood.playing, false); await shot('cheia-guiada'); });
  await record(); await mission();
  await check('roteiro fecha com Esc sem acionar a cena', async () => { const old = (await observe()).view; await page.keyboard.press('v'); assert.equal((await observe()).view, old); await page.keyboard.press('Escape'); assert.equal(await page.locator('#mission').evaluate(e => e.open), false); });
  await page.locator('.education-tools a').click(); await page.locator('.school-tabs a[href="#atividades"]').click();
  await check('quatro registros comparáveis e limpeza explícita', async () => { assert.equal(await page.locator('#records tbody tr').count(), 4); await shot('registros-comparados'); await page.locator('#clear-records').click(); assert.equal(await page.locator('#records tbody tr').count(), 0); });
  await page.locator('.school-tabs a[href="#professor"]').click();
  await check('plano cobre 50 minutos e declara relação parcial com BNCC', async () => { assert.equal(await page.locator('.lesson-plan li').count(), 5); for (const code of ['EF06GE04', 'EF06GE09', 'EF07GE11']) assert.match(await page.locator('#professor').textContent(), new RegExp(code)); assert.match(await page.locator('#professor').textContent(), /sem certificação ou cobertura integral/); await shot('professor'); });
  await check('impressão do plano mantém só o conteúdo do professor', async () => { await page.locator('#professor details').evaluate(e => { e.open = true; }); await page.emulateMedia({ media: 'print' }); assert.equal(await page.locator('#professor').isVisible(), true); assert.equal(await page.locator('.hero').isVisible(), false); assert.equal(await page.locator('.teacher-actions').isVisible(), false); await shot('plano-impressao'); await page.emulateMedia({ media: 'screen' }); });
  await check('ficha abre sem código 3D e possui espaços para registros', async () => { const p = await context.newPage(); const r = await p.goto(new URL('ficha.html', base).href); assert.equal(r.status(), 200); assert.equal(await p.locator('h2').count(), 5); assert.equal(await p.locator('canvas').count(), 0); await p.emulateMedia({ media: 'print' }); assert.equal(await p.locator('button').isVisible(), false); await p.screenshot({ path: fileURLToPath(new URL('ficha-impressao.png', destination)), fullPage: true }); await p.close(); });
  await page.waitForFunction(() => document.querySelector('#offline-status').textContent.startsWith('Materiais disponíveis'));
  await check('cache offline contém os materiais completos', async () => { const paths = await page.evaluate(async () => { const keys = await caches.keys(); const cache = await caches.open(keys.find(k => k.startsWith('atlas-amazonas-'))); return (await cache.keys()).map(r => new URL(r.url).pathname); }); for (const path of ['/escola.html', '/', '/ficha.html', '/geografia/regiao-amazonica-ana.pdf', '/geografia/regiao-amazonica-ana.jpg', '/geografia/amazonas-parintins-nasa.jpg', '/audio/river-ambience.ogg']) assert.ok(paths.includes(path), path); });
  await context.setOffline(true);
  await check('caderno, cena, foto, mapa e ficha reabrem sem internet', async () => { await page.goto(new URL('escola.html', base).href, { waitUntil: 'load' }); assert.equal(await page.locator('.hero img').evaluate(e => e.complete && e.naturalWidth > 0), true); assert.equal(await page.locator('#official-map').evaluate(e => e.complete && e.naturalWidth > 0), true); await page.goto(new URL('laboratorio.html?atividade=cheias', base).href, { waitUntil: 'load' }); await page.waitForFunction(() => window.__AMAZONAS__?.ready); await preset('Comparar cheia'); assert.ok((await observe()).rendered.triangles > 100000); await page.goto(new URL('ficha.html', base).href, { waitUntil: 'load' }); assert.equal(await page.locator('h2').count(), 5); await page.goto(new URL('escola.html#professor', base).href, { waitUntil: 'load' }); await shot('professor-offline'); });
  await context.setOffline(false);
  for (const [width, height, name] of [[390, 844, 'celular'], [844, 390, 'paisagem'], [1024, 768, 'tablet']]) {
    await check(`caderno em ${name}: leitura e três abas sem transbordamento`, async () => { await page.setViewportSize({ width, height }); for (const id of ['estudar', 'atividades', 'professor']) { await page.locator(`.school-tabs a[href="#${id}"]`).click(); assert.equal(await page.locator(`#${id}`).isVisible(), true); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); await shot(`${name}-${id}`); } });
  }
  await check('caderno permite ampliação de 200%', async () => { await page.setViewportSize({ width: 1440, height: 1000 }); await page.locator('.school-tabs a[href="#estudar"]').click(); await page.evaluate(() => { document.body.style.zoom = '2'; }); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); await shot('texto-ampliado'); });
  await check('caderno funciona quando WebGL está indisponível', async () => { const p = await context.newPage(); await p.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(type, ...args) { return type.startsWith('webgl') ? null : original.call(this, type, ...args); }; }); await p.goto(new URL('escola.html', base).href); assert.equal(await p.locator('h1').textContent(), 'Um rio.Muitas paisagens.'); await p.locator('.school-tabs a[href="#atividades"]').click(); assert.equal(await p.locator('#quiz fieldset').count(), 5); await p.goto(new URL('laboratorio.html', base).href); await p.waitForFunction(() => document.querySelector('#loading').textContent.includes('não está disponível')); assert.equal(await p.locator('#loading a').getAttribute('href'), '/escola.html'); await p.close(); });
  await check('caderno e ficha têm leitura sem JavaScript', async () => { const nojs = await browser.newContext({ javaScriptEnabled: false }); const p = await nojs.newPage(); await p.goto(new URL('escola.html', base).href); assert.ok(await p.locator('#estudar').isVisible()); await p.goto(new URL('ficha.html', base).href); assert.equal(await p.locator('h2').count(), 5); await nojs.close(); });
  await check('console limpo e recursos servidos iguais à produção', async () => { assert.deepEqual(errors, []); for (const resource of assets) { const path = new URL(resource).pathname === '/' ? 'index.html' : decodeURIComponent(new URL(resource).pathname).slice(1); const local = await readFile(new URL(`../dist/${path}`, import.meta.url)); const r = await fetch(resource); assert.equal(r.status, 200); const sha256 = createHash('sha256').update(local).digest('hex'); assert.equal(createHash('sha256').update(Buffer.from(await r.arrayBuffer())).digest('hex'), sha256, path); proof.push({ path, sha256 }); } });
  report = { status: 'passed', url: new URL('escola.html', base).href, commit: served.commit, cases, passed: cases.length, errors, proof, mobile: 'Emulado; não testado em dispositivo físico.', pedagogy: 'Sem aplicação com turma real ou certificação curricular.' };
} catch (error) { report = { status: 'failed', cases, passed: cases.length, errors, failure: error.stack }; process.exitCode = 1; }
finally { await writeFile(new URL('report.json', destination), JSON.stringify(report, null, 2)); await browser.close(); }
console.log(JSON.stringify({ status: report.status, passed: report.passed, errors, failure: report.failure }));
